// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (short_code, original_url) VALUES (?, ?) RETURNING id, short_code, original_url, created_at, access_count
`

type CreateURLParams struct {
	ShortCode   string
	OriginalUrl string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL, arg.ShortCode, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.AccessCount,
	)
	return i, err
}

const getAllURLs = `-- name: GetAllURLs :many
SELECT id, short_code, original_url, created_at, access_count FROM urls ORDER BY created_at DESC
`

func (q *Queries) GetAllURLs(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getAllURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.CreatedAt,
			&i.AccessCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURL = `-- name: GetURL :one
SELECT id, short_code, original_url, created_at, access_count FROM urls WHERE short_code = ?
`

func (q *Queries) GetURL(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURL, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.AccessCount,
	)
	return i, err
}

const updateAccessCount = `-- name: UpdateAccessCount :exec
UPDATE urls SET access_count = access_count + 1 WHERE short_code = ?
`

func (q *Queries) UpdateAccessCount(ctx context.Context, shortCode string) error {
	_, err := q.db.ExecContext(ctx, updateAccessCount, shortCode)
	return err
}
